version: "3.8"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp_user
            MYSQL_PASSWORD: wp_pass
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - mysql_data:/var/lib/mysql

    wordpress:
        image: wordpress:latest
        container_name: wordpress-site
        depends_on:
            - mysql
        ports:
            - "8080:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wp_user
            WORDPRESS_DB_PASSWORD: wp_pass
        volumes:
            - wordpress_data:/var/www/html

volumes:
    mysql_data:
    wordpress_data:
