services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    container_name: node_app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
