version: "3.8"
services:
    db:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wordpressdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - wpnet
    wordpress:
        image: wordpress:latest
        container_name: wordpress-site
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpressdb
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
        networks:
            - wpnet
volumes:
    db_data:
networks:
    wpnet:
        driver: bridge
