version: "3.8"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: testdb
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    node-app:
        build: .
        container_name: node-app
        depends_on:
            - mysql
        restart: always

volumes:
    mysql_data:
